institute: "Heidelberg, Max Planck Inst."

# lower_date and upper_date defined here is only used
# to generate the cache file
lower_date: '2006-01-01'
upper_date: null
size: 200 # 500 is also a good value but bad internet connection may cause problems

keywords:
  - "neutrino"
  - "bsm"
  - "darkmatter"
  - "Dark Matter"
  - "dm"
  - "double beta decay"
  - "double chooz"
  - "Double beta decay"
  - "conus"
  - "stereo"
  - "xenon"
  - "XENON"
  - "darwin"
  - "borexino"
  - "gerda"
  - "legend"
  - "neutrino: oscillation"
  - "neutrino: mixing"
  - "double-beta decay"
  - "symmetry breaking"
  - "Higgs particle: mass"
  - "renormalization group"

people_to_exclude:
  - "Blaum"
  - "Tuffs"
